CV/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from CV_APP.views import cv, coordinacion, rectores, psicologa


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CV_APP.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/coordinador/', coordinacion.CoordinadorSignUpView.as_view(), name='coordinador_signup'),
    path('accounts/coordinador2/', coordinacion.CoordinadorSignUpView2.as_view(), name='coordinador_signup2'),
    path('accounts/rector/', rectores.RectorSignUpView.as_view(), name='rector_signup'),
    path('accounts/psicologa/', psicologa.PsicologaSignUpView.as_view(), name='psicologa_signup'),




]

CV_APP/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from .views import cv, coordinacion, rectores, psicologa, monica
urlpatterns = [
    path('postulacion', cv.index, name='index'),
    path('', cv.home, name='home'),
    path('user_profile', cv.user_profile, name='user'),
    path('ajax/load-indi/', cv.load_indi, name='ajax_load_indi'),

    path('coordinacion/', include(([
        path('postulantes', coordinacion.index, name='index'),
        path('rechazados', coordinacion.rechazados, name='rechazados'),
        path('finalizado', coordinacion.finalizados, name='fin'),
        path('finalizados', coordinacion.finalizados_c, name='fin_c'),
        path('finalizados_em', coordinacion.finalizados_em, name='fin_em'),
        path('ficha_fat', coordinacion.carta_oferta, name='ficha_fat'),
        path('ficha_fat_c', coordinacion.carta_oferta_c, name='ficha_fat_c'),
        path('ficha_fat_em', coordinacion.carta_oferta_em, name='ficha_fat_em'),


        path('postulante/<int:pk>/liberar_c/', coordinacion.liberar_c, name='liberar_c'),

        path('coordinadores', coordinacion.index_c, name='coordinadores'),
        path('coordinadores/entrevistar', coordinacion.entrevistar_c, name='entrevistar'),
        path('coordinadores/<int:pk>/rubrica/', coordinacion.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/rubricas/', coordinacion.rubricas, name='rubricas'),
        path('equipomulti/estado_em', coordinacion.estado_em, name='estado_em'),

        path('equipomulti', coordinacion.index_equipomulti, name='equipo_multi'),


        path('postulantes/<int:pk>/rubrica_rector/', coordinacion.vista_rubrica, name='vista_rubrica'),
        path('coordinadores/<int:pk>/rubrica_coordinador/', coordinacion.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', coordinacion.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', coordinacion.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', coordinacion.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('postulantes/<int:pk>/vista_rubrica_coordinador/', coordinacion.vista_rubricaC, name='vista_rubrica_coordinador'),

        path('activos', coordinacion.activos, name='activos'),
        path('proceso', coordinacion.proceso, name='proceso'),
        path('psicolaboral', coordinacion.psicolaboral, name='psicolaboral'),
        path('psicolaboral_coordinador', coordinacion.psicolaboral_c, name='psicolaboral_c'),
        path('psicolaboral_equipomulti', coordinacion.psicolaboral_em, name='psicolaboral_em'),
        path('postulante/<int:pk>/finalizar', coordinacion.finalizar, name='finalizar'),
        path('postulantes/<int:pk>/', coordinacion.info, name='info'),
        path('postulantes/<int:pk>/delete', coordinacion.PostulanteDeleteView.as_view(), name='borrar'),
    ], 'CV_APP'), namespace='coordinacion')),

    path('rectores/', include(([
        path('postulantes', rectores.index, name='index'),
        path('postulantes/<int:pk>/', rectores.info, name='info'),
        path('postulantes/rechazados/', rectores.cargo, name='rechazados'),
        path('postulantes/clasedemo/', rectores.clasedemo, name='clasedemo'),
        path('postulantes/oferta/', rectores.oferta_view, name='oferta_view'),

        path('postulantes/entrevistas/', rectores.entrevista, name='entrevistas'),
        path('postulantes/<int:pk>/rubricas/', rectores.rubricas, name='rubricas'),
        path('postulantes/<int:pk>/rubrica/', rectores.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/vista_rubrica/', rectores.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', rectores.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', rectores.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', rectores.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/vista_rubrica_coordinador/', rectores.vista_rubricaC, name='vista_rubrica_coordinador'),

        path('postulantes/<int:pk>/rubrica_equipo/', rectores.rubricaem, name='rubrica_em'),
        path('postulantes/<int:pk>/rubrica_demo/', rectores.rubricademo, name='rubrica_demo'),
        path('postulantes/<int:pk>/rubrica_coordinador/', rectores.rubrica_coordinador, name='rubrica_coordinador'),
        path('postulantes/<int:pk>/send/', rectores.send, name='send'),
        path('postulantes/<int:pk>/reportar/', rectores.reportar, name='reportar'),
        path('postulantes/<int:pk>/ficha/', rectores.subirficha, name='ficha'),
        path('postulantes/<int:pk>/oferta_laboral/', rectores.oferta, name='oferta'),
        path('finalizado', rectores.finalizados, name='fin'),
        path('postulantes/aprobados/',rectores.aprobados, name='aprobados'),
    ], 'CV_APP'), namespace='rectores')),

    path('psicologa/', include(([
        path('postulantes', psicologa.index, name='index'),
        path('postulantes/<int:pk>/vista_rubrica/', psicologa.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/rubrica_coordinador/',psicologa.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/rubrica_psicologica/', psicologa.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/rubrica_psicologica_edit/', psicologa.rubrica_edit, name='rubrica_edit'),

        path('postulantes/entrevistados/',psicologa.entrevistados, name='entrevistados'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', psicologa.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/rubricas/', psicologa.rubricas, name='rubricas'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', psicologa.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', psicologa.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('rechazados', psicologa.rechazados, name='rechazados'),
        path('postulantes/<int:pk>/', psicologa.info, name='info'),

    ], 'CV_APP'), namespace='psicologa')),

    path('monica/', include(([
        path('postulantes/', monica.postulantes, name='postulantes'),
        path('postulantes/index/', monica.index, name='index'),
        path('postulantes/<int:pk>/vista_rubrica/', monica.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/rubrica_coordinador/',monica.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', monica.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/rubricas/', monica.rubricas, name='rubricas'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', monica.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', monica.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('rechazados', monica.rechazados, name='rechazados'),
        path('postulantes/<int:pk>/', monica.info, name='info'),

        path('finalizado', monica.finalizados, name='fin'),
    ], 'CV_APP'), namespace='monica')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CV_APP/views/cv.py
import json
import traceback
from itertools import chain
from .__init__ import *
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from django.contrib.contenttypes.models import ContentType
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, PatternFill, Font, Side
from openpyxl.drawing.image import Image
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template,render_to_string
from django.utils.html import strip_tags
from django.template import Context
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count, Sum, Min, Max, Func
from django.contrib.auth.models import User
from django.forms import inlineformset_factory, modelformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (TemplateView,CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from CV_APP.models import Años, Cargo, Colegios, Disposicion, Postulacion, User, Cargo, Titulo
from CV_APP.forms import PostulacionForm

def home(request):
    if request.user.is_authenticated:
        if request.user.is_coordinacion:
            return redirect('coordinacion:proceso')
        if request.user.is_coordinacion2:
            return redirect('coordinacion:proceso')
        if request.user.is_rector:
            return redirect('rectores:index')
        if request.user.is_psicologa:
            return redirect('psicologa:index')
        if request.user.is_monica:
            return redirect('monica:postulantes')
    return render(request, 'index.html')


def index(request):

    if request.method == 'POST':
        form = PostulacionForm(request.POST, request.FILES)
        if form.is_valid():
            postulacion = form.save(commit=False)
            if Postulacion.objects.filter(rut=postulacion.rut):
                messages.error(request, 'Tiene una postulación en proceso.')
            else:

                if postulacion.cargo.id == 6:

                    postulacion.valido = True
                    postulacion.save()
                    form.save_m2m()
                    subject = "Postulación recibida"
                    html_body = render_to_string("mail.html")
                    msg = EmailMultiAlternatives(subject=subject, from_email="postulaciones@bostoneduca.cl",
                        to=[postulacion.email], body=html_body)
                    msg.attach_alternative(html_body, "text/html")
                    msg.send()
                    messages.success(request, '¡Felicidades! Has completado exitosamente el formulario de postulación laboral online. Pronto serás notificado si cumples con el perfil que estamos buscando y si existen vacantes al cargo que postulaste.')

                    return redirect('index')
                else:
                    postulacion.valido = True
                    postulacion.save()
                    form.save_m2m()

                    subject = "Postulación Recibida"
                    html_body = render_to_string("mail.html")
                    msg = EmailMultiAlternatives(subject=subject, from_email="postulaciones@bostoneduca.cl",
                        to=[postulacion.email], body=html_body)
                    msg.attach_alternative(html_body, "text/html")
                    msg.send()
                    messages.success(request, '¡Felicidades! Has completado exitosamente el formulario de postulación laboral online. Pronto serás notificado si cumples con el perfil que estamos buscando y si existen vacantes al cargo que postulaste.')

                    return redirect('index')
    else:
        form = PostulacionForm()

    return render(request, "home.html",{
        'form':form,
       'submit':True,
    })


def load_indi(request):
    cargo_id = request.GET.get('cargo')
    titulo = Titulo.objects.filter(cargo__id=cargo_id).all
    return render(request, 'dropdown.html', {'titulo':titulo})


def user_profile(request):

    return render(request, "user_profile.html")

CV_APP/templates/coordinacion/finalizado.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'coordinacion/header.html' with active='new4' %}

<br>
<div id="popup"></div>

<div class="table-responsive">
    <table id="example" class="table table-striped table-bordered display table-sm">
        <thead>
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">Postulante</th>
                <th class="text-center">Cargo</th>
                <th class="text-center">Nivel de inglés</th>

                <th class="text-center">Título</th>
                <th class="text-center">Colegio</th>
                <th class="text-center">Estado</th>
                <th class="text-center">Rúbricas aplicadas</th>

            </tr>
        </thead>

        <tbody>
        {% for postulante in postulante %}
        {% if postulante.cargo.id == 6 or postulante.cargo.id == 7 %}
            {% else %}
            <tr>
                <td class="text-center">{{forloop.counter}}</td>

                <td class="text-center">
                    <a onclick="return abrir_modal('{% url 'coordinacion:info' postulante.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulante.nombre}} {{postulante.apellido_p}} {{postulante.apellido_m}}</a>
                </td>
                <td class="text-center">
                    {{postulante.cargo}}
                </td>
                <td class="text-center">{{postulante.nivel_ingles}}</td>

                <td class="text-center">{{postulante.titulo}}</td>
                <td class="text-center">{{postulante.colegio1}}</td>
                {% if postulante.aceptada == True %}
                <td class="text-center"> <span class="badge badge-pill badge-success ">Oferta aceptada</span> </td>
                {% endif %}
                <td class="text-center"><a href="{% url 'coordinacion:rubricas' postulante.pk %}" class="btn btn-primary btn-sm"> Rúbricas</a></td>
            </tr>
            {% endif %}

        {% endfor %}
        </tbody>
    </table>


</div>

<script>
    var modal;
    function abrir_modal(url, titulo)
    {
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 900,
            resizable: false
        }).dialog('open').load(url)
    }

    function cerrar_modal()
    {
        modal.dialog("close");
    }
</script>
{% endblock %}

CV_APP/templates/coordinacion/header.html
{% if user.is_authenticated and user.is_coordinacion %}
{% load static %}
<!--<link rel="stylesheet" href="{% static "css/menu.css" %}">-->

<img class="img-thumbnail" src="{% static "img/logo.jpg" %}" alt="" width="200" height="100">
<div class="text-right">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i>  {{ user.first_name }}  {{user.last_name}}<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'user' %}" target="_blank"> <i class="fas fa-user-cog"></i> Información de Usuario</a></li>
    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a></li>
  </ul>
</div>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link  active" href="{% url 'coordinacion:proceso' %}">Docentes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link " href="{% url 'coordinacion:coordinadores' %}">Coordinadores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:estado_em' %}">Equipo Multidisciplinario</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:rechazados' %}">No sigue proceso</a>
  </li>
</ul>


<br>

{% endif %}
{% if user.is_authenticated and user.is_coordinacion2 %}
{% load static %}
<!--<link rel="stylesheet" href="{% static "css/menu.css" %}">-->

<img class="img-thumbnail" src="{% static "img/logo.jpg" %}" alt="" width="200" height="100">
<div class="text-right">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i>  {{ user.first_name }}  {{user.last_name}}<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'user' %}" target="_blank"> <i class="fas fa-user-cog"></i> Información de Usuario</a></li>
    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a></li>
  </ul>
</div>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link  active" href="{% url 'coordinacion:proceso' %}">Docentes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link " href="{% url 'coordinacion:coordinadores' %}">Coordinadores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:estado_em' %}">Equipo Multidisciplinario</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:rechazados' %}">No sigue proceso</a>
  </li>
</ul>


<br>

{% endif %}
<ul class="nav nav-tabs">
    <!--
    <li class="nav-item">
      <a class="nav-link {% if active == 'new' %} active{% endif %}"" href="{% url 'coordinacion:index' %}">Postulantes</a>
    </li>
    -->
   <!-- <li class="nav-item">
      <a class="nav-link {% if active == 'new2' %} active{% endif %}"" href="{% url 'coordinacion:activos' %}">Activos</a>
    </li>-->
    <li class="nav-item">
        <a class="nav-link {% if active == 'new3' %} active{% endif %}"" href="{% url 'coordinacion:proceso' %}">Estado Postulante</a>
    </li>
   <li class="nav-item">
      <a class="nav-link {% if active == 'new5' %} active{% endif %}"" href="{% url 'coordinacion:psicolaboral' %}">Liberar psicolaboral</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if active == 'new6' %} active{% endif %}"" href="{% url 'coordinacion:ficha_fat' %}">Aceptar ficha F.A.T</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if active == 'new4' %} active{% endif %}"" href="{% url 'coordinacion:fin' %}">Finalizados</a>
    </li>
</ul>

CV_APP/templates/coordinacion/header_c.html
{% if user.is_authenticated and user.is_coordinacion %}
{% load static %}
<!--<link rel="stylesheet" href="{% static "css/menu.css" %}">-->
<img class="img-thumbnail" src="{% static "img/logo.jpg" %}" alt="" width="200" height="100">
<div class="text-right">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i>  {{ user.first_name }}  {{user.last_name}}<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'user' %}" target="_blank"> <i class="fas fa-user-cog"></i> Información de Usuario</a></li>
    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a></li>
  </ul>
</div>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link  " href="{% url 'coordinacion:proceso' %}">Docentes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'coordinacion:coordinadores' %}">Coordinadores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:estado_em' %}">Equipo Multidisciplinario</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:rechazados' %}">No sigue proceso</a>
  </li>
</ul>


<br>

{% endif %}
{% if user.is_authenticated and user.is_coordinacion2 %}
{% load static %}
<!--<link rel="stylesheet" href="{% static "css/menu.css" %}">-->
<img class="img-thumbnail" src="{% static "img/logo.jpg" %}" alt="" width="200" height="100">
<div class="text-right">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i>  {{ user.first_name }}  {{user.last_name}}<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'user' %}" target="_blank"> <i class="fas fa-user-cog"></i> Información de Usuario</a></li>
    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a></li>
  </ul>
</div>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link  " href="{% url 'coordinacion:proceso' %}">Docentes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'coordinacion:coordinadores' %}">Coordinadores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:estado_em' %}">Equipo Multidisciplinario</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:rechazados' %}">No sigue proceso</a>
  </li>
</ul>


<br>

{% endif %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link {% if active == 'new' %} active{% endif %}" href="{% url 'coordinacion:coordinadores' %}">Postulantes</a>
  </li>

  <li class="nav-item">
    <a class="nav-link {% if active == 'new2' %} active{% endif %}" href="{% url 'coordinacion:entrevistar' %}">Estado postulante</a>
  </li>

  <li class="nav-item">
    <a class="nav-link {% if active == 'new3' %} active{% endif %}" href="{% url 'coordinacion:psicolaboral_c' %}">Liberar Psicolaboral</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if active == 'new6' %} active{% endif %}"" href="{% url 'coordinacion:ficha_fat_c' %}">Aceptar ficha F.A.T</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if active == 'new4' %} active{% endif %}" href="{% url 'coordinacion:fin_c' %}">Finalizados</a>
  </li>
</ul>

CV_APP/templates/coordinacion/header_equi.html
{% if user.is_authenticated and user.is_coordinacion %}
{% load static %}
<!--<link rel="stylesheet" href="{% static "css/menu.css" %}">-->
<img class="img-thumbnail" src="{% static "img/logo.jpg" %}" alt="" width="200" height="100">
<div class="text-right">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i>  {{ user.first_name }}  {{user.last_name}}<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'user' %}" target="_blank"> <i class="fas fa-user-cog"></i> Información de Usuario</a></li>
    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a></li>
  </ul>
</div>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link  " href="{% url 'coordinacion:proceso' %}">Docentes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:coordinadores' %}">Coordinadores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'coordinacion:estado_em' %}">Equipo Multidisciplinario</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:rechazados' %}">No sigue proceso</a>
  </li>
</ul>


<br>

{% endif %}
{% if user.is_authenticated and user.is_coordinacion2 %}
{% load static %}
<!--<link rel="stylesheet" href="{% static "css/menu.css" %}">-->
<img class="img-thumbnail" src="{% static "img/logo.jpg" %}" alt="" width="200" height="100">
<div class="text-right">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i>  {{ user.first_name }}  {{user.last_name}}<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'user' %}" target="_blank"> <i class="fas fa-user-cog"></i> Información de Usuario</a></li>
    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a></li>
  </ul>
</div>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link  " href="{% url 'coordinacion:proceso' %}">Docentes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:coordinadores' %}">Coordinadores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'coordinacion:estado_em' %}">Equipo Multidisciplinario</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'coordinacion:rechazados' %}">No sigue proceso</a>
  </li>
</ul>


<br>

{% endif %}

<ul class="nav nav-tabs">
    <!--
  <li class="nav-item">
    <a class="nav-link {% if active == 'new' %} active{% endif %}" href="{% url 'coordinacion:equipo_multi' %}">Postulantes</a>
  </li>
-->
  <li class="nav-item">
    <a class="nav-link {% if active == 'new2' %} active{% endif %}" href="{% url 'coordinacion:estado_em' %}">Estado postulante</a>
  </li>

  <li class="nav-item">
    <a class="nav-link {% if active == 'new3' %} active{% endif %}" href="{% url 'coordinacion:psicolaboral_em' %}">Liberar Psicolaboral</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if active == 'new6' %} active{% endif %}"" href="{% url 'coordinacion:ficha_fat_em' %}">Aceptar ficha F.A.T</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if active == 'new4' %} active{% endif %}" href="{% url 'coordinacion:fin_em' %}">Finalizados</a>
  </li>
</ul>