CV/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from CV_APP.views import cv, coordinacion, rectores, psicologa


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CV_APP.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/coordinador/', coordinacion.CoordinadorSignUpView.as_view(), name='coordinador_signup'),
    path('accounts/coordinador2/', coordinacion.CoordinadorSignUpView2.as_view(), name='coordinador_signup2'),
    path('accounts/rector/', rectores.RectorSignUpView.as_view(), name='rector_signup'),
    path('accounts/psicologa/', psicologa.PsicologaSignUpView.as_view(), name='psicologa_signup'),




]

CV_APP/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from .views import cv, coordinacion, rectores, psicologa, monica
urlpatterns = [
    path('postulacion', cv.index, name='index'),
    path('', cv.home, name='home'),
    path('user_profile', cv.user_profile, name='user'),
    path('ajax/load-indi/', cv.load_indi, name='ajax_load_indi'),

    path('coordinacion/', include(([
        path('postulantes', coordinacion.index, name='index'),
        path('rechazados', coordinacion.rechazados, name='rechazados'),
        path('finalizado', coordinacion.finalizados, name='fin'),
        path('finalizados', coordinacion.finalizados_c, name='fin_c'),
        path('finalizados_em', coordinacion.finalizados_em, name='fin_em'),
        path('ficha_fat', coordinacion.carta_oferta, name='ficha_fat'),
        path('ficha_fat_c', coordinacion.carta_oferta_c, name='ficha_fat_c'),
        path('ficha_fat_em', coordinacion.carta_oferta_em, name='ficha_fat_em'),


        path('postulante/<int:pk>/liberar_c/', coordinacion.liberar_c, name='liberar_c'),

        path('coordinadores', coordinacion.index_c, name='coordinadores'),
        path('coordinadores/entrevistar', coordinacion.entrevistar_c, name='entrevistar'),
        path('coordinadores/<int:pk>/rubrica/', coordinacion.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/rubricas/', coordinacion.rubricas, name='rubricas'),
        path('equipomulti/estado_em', coordinacion.estado_em, name='estado_em'),

        path('equipomulti', coordinacion.index_equipomulti, name='equipo_multi'),


        path('postulantes/<int:pk>/rubrica_rector/', coordinacion.vista_rubrica, name='vista_rubrica'),
        path('coordinadores/<int:pk>/rubrica_coordinador/', coordinacion.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', coordinacion.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', coordinacion.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', coordinacion.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('postulantes/<int:pk>/vista_rubrica_coordinador/', coordinacion.vista_rubricaC, name='vista_rubrica_coordinador'),

        path('activos', coordinacion.activos, name='activos'),
        path('proceso', coordinacion.proceso, name='proceso'),
        path('psicolaboral', coordinacion.psicolaboral, name='psicolaboral'),
        path('psicolaboral_coordinador', coordinacion.psicolaboral_c, name='psicolaboral_c'),
        path('psicolaboral_equipomulti', coordinacion.psicolaboral_em, name='psicolaboral_em'),
        path('postulante/<int:pk>/finalizar', coordinacion.finalizar, name='finalizar'),
        path('postulantes/<int:pk>/', coordinacion.info, name='info'),
        path('postulantes/<int:pk>/delete', coordinacion.PostulanteDeleteView.as_view(), name='borrar'),
    ], 'CV_APP'), namespace='coordinacion')),

    path('rectores/', include(([
        path('postulantes', rectores.index, name='index'),
        path('postulantes/<int:pk>/', rectores.info, name='info'),
        path('postulantes/rechazados/', rectores.cargo, name='rechazados'),
        path('postulantes/clasedemo/', rectores.clasedemo, name='clasedemo'),
        path('postulantes/oferta/', rectores.oferta_view, name='oferta_view'),

        path('postulantes/entrevistas/', rectores.entrevista, name='entrevistas'),
        path('postulantes/<int:pk>/rubricas/', rectores.rubricas, name='rubricas'),
        path('postulantes/<int:pk>/rubrica/', rectores.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/vista_rubrica/', rectores.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', rectores.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', rectores.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', rectores.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/vista_rubrica_coordinador/', rectores.vista_rubricaC, name='vista_rubrica_coordinador'),

        path('postulantes/<int:pk>/rubrica_equipo/', rectores.rubricaem, name='rubrica_em'),
        path('postulantes/<int:pk>/rubrica_demo/', rectores.rubricademo, name='rubrica_demo'),
        path('postulantes/<int:pk>/rubrica_coordinador/', rectores.rubrica_coordinador, name='rubrica_coordinador'),
        path('postulantes/<int:pk>/send/', rectores.send, name='send'),
        path('postulantes/<int:pk>/reportar/', rectores.reportar, name='reportar'),
        path('postulantes/<int:pk>/ficha/', rectores.subirficha, name='ficha'),
        path('postulantes/<int:pk>/oferta_laboral/', rectores.oferta, name='oferta'),
        path('finalizado', rectores.finalizados, name='fin'),
        path('postulantes/aprobados/',rectores.aprobados, name='aprobados'),
    ], 'CV_APP'), namespace='rectores')),

    path('psicologa/', include(([
        path('postulantes', psicologa.index, name='index'),
        path('postulantes/<int:pk>/vista_rubrica/', psicologa.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/rubrica_coordinador/',psicologa.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/rubrica_psicologica/', psicologa.rubrica, name='rubrica'),
        path('postulantes/<int:pk>/rubrica_psicologica_edit/', psicologa.rubrica_edit, name='rubrica_edit'),

        path('postulantes/entrevistados/',psicologa.entrevistados, name='entrevistados'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', psicologa.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/rubricas/', psicologa.rubricas, name='rubricas'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', psicologa.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', psicologa.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('rechazados', psicologa.rechazados, name='rechazados'),
        path('postulantes/<int:pk>/', psicologa.info, name='info'),

    ], 'CV_APP'), namespace='psicologa')),

    path('monica/', include(([
        path('postulantes/', monica.postulantes, name='postulantes'),
        path('postulantes/index/', monica.index, name='index'),
        path('postulantes/<int:pk>/vista_rubrica/', monica.vista_rubrica, name='vista_rubrica'),
        path('postulantes/<int:pk>/rubrica_coordinador/',monica.vista_rubricaC, name='vista_rubrica_coordinador'),
        path('postulantes/<int:pk>/vista_rubrica_psicologa/', monica.vista_rubrica_psicologa, name='vista_rubrica_psicologa'),
        path('postulantes/<int:pk>/rubricas/', monica.rubricas, name='rubricas'),
        path('postulantes/<int:pk>/vista_rubrica_equipo/', monica.vista_rubrica_equipo, name='vista_rubrica_equipo'),
        path('postulantes/<int:pk>/vista_rubrica_demo/', monica.vista_rubrica_demo, name='vista_rubrica_demo'),
        path('rechazados', monica.rechazados, name='rechazados'),
        path('postulantes/<int:pk>/', monica.info, name='info'),

        path('finalizado', monica.finalizados, name='fin'),
    ], 'CV_APP'), namespace='monica')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CV_APP/views/cv.py
import json
import traceback
from itertools import chain
from .__init__ import *
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from django.contrib.contenttypes.models import ContentType
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, PatternFill, Font, Side
from openpyxl.drawing.image import Image
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template,render_to_string
from django.utils.html import strip_tags
from django.template import Context
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count, Sum, Min, Max, Func
from django.contrib.auth.models import User
from django.forms import inlineformset_factory, modelformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (TemplateView,CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from CV_APP.models import Años, Cargo, Colegios, Disposicion, Postulacion, User, Cargo, Titulo
from CV_APP.forms import PostulacionForm

def home(request):
    if request.user.is_authenticated:
        if request.user.is_coordinacion:
            return redirect('coordinacion:proceso')
        if request.user.is_coordinacion2:
            return redirect('coordinacion:proceso')
        if request.user.is_rector:
            return redirect('rectores:index')
        if request.user.is_psicologa:
            return redirect('psicologa:index')
        if request.user.is_monica:
            return redirect('monica:postulantes')
    return render(request, 'index.html')


def index(request):

    if request.method == 'POST':
        form = PostulacionForm(request.POST, request.FILES)
        if form.is_valid():
            postulacion = form.save(commit=False)
            if Postulacion.objects.filter(rut=postulacion.rut):
                messages.error(request, 'Tiene una postulación en proceso.')
            else:

                if postulacion.cargo.id == 6:

                    postulacion.valido = True
                    postulacion.save()
                    form.save_m2m()
                    subject = "Postulación recibida"
                    html_body = render_to_string("mail.html")
                    msg = EmailMultiAlternatives(subject=subject, from_email="postulaciones@bostoneduca.cl",
                        to=[postulacion.email], body=html_body)
                    msg.attach_alternative(html_body, "text/html")
                    msg.send()
                    messages.success(request, '¡Felicidades! Has completado exitosamente el formulario de postulación laboral online. Pronto serás notificado si cumples con el perfil que estamos buscando y si existen vacantes al cargo que postulaste.')

                    return redirect('index')
                else:
                    postulacion.valido = True
                    postulacion.save()
                    form.save_m2m()

                    subject = "Postulación Recibida"
                    html_body = render_to_string("mail.html")
                    msg = EmailMultiAlternatives(subject=subject, from_email="postulaciones@bostoneduca.cl",
                        to=[postulacion.email], body=html_body)
                    msg.attach_alternative(html_body, "text/html")
                    msg.send()
                    messages.success(request, '¡Felicidades! Has completado exitosamente el formulario de postulación laboral online. Pronto serás notificado si cumples con el perfil que estamos buscando y si existen vacantes al cargo que postulaste.')

                    return redirect('index')
    else:
        form = PostulacionForm()

    return render(request, "home.html",{
        'form':form,
       'submit':True,
    })


def load_indi(request):
    cargo_id = request.GET.get('cargo')
    titulo = Titulo.objects.filter(cargo__id=cargo_id).all
    return render(request, 'dropdown.html', {'titulo':titulo})


def user_profile(request):

    return render(request, "user_profile.html")

CV_APP/templates/psicologa/header.html
{% load static %}
<!--<link rel="stylesheet" href="{% static "css/menu.css" %}">-->

<img class="img-thumbnail" src="{% static "img/logo.jpg" %}" alt="" width="200" height="100">


<div class="text-right">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i> {{ user.first_name }}  {{user.last_name}}<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'user' %}" target="_blank"> <i class="fas fa-user-cog"></i> Información de Usuario</a></li>
    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Salir</a></li>
  </ul>
</div>


<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {% if active == 'new' %} active{% endif %}"  href="{% url 'psicologa:index' %}"  >Postulantes</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if active == 'new2' %} active{% endif %} " href="{% url 'psicologa:entrevistados' %}">Evaluados</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if active == 'new3' %} active{% endif %} " href="{% url 'psicologa:rechazados' %}">No sigue proceso</a>
    </li>
</ul>

CV_APP/templates/psicologa/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


{% include 'psicologa/header.html' with active='new' %}

<br>

<div class="table-responsive">
    <table id="example" class=" table table-striped table-bordered display table-sm" >
        <thead>
            <tr>
                <th style="text-align: center;" scope="col">Postulante</th>
                <th style="text-align: center;" scope="col">Cargo</th>
                <th style="text-align: center;" scope="col">Colegio</th>
                <th style="text-align: center;" scope="col">Años Experiencia</th>
                <th style="text-align: center;" scope="col">CV</th>
                <th style="text-align: center;" scope="col">Fecha de postulación</th>

                <th class="text-center">Rúbricas aplicadas</th>
                <th>Rúbrica</th>

            </tr>
        </thead>

        <tbody>
        {% for postulante in postulantes %}
        {% if user.psicologa.psicologa1 %}
        {% if postulante.psicologa1 %}
            <tr>
                <td class="text-center">
                    <a onclick="return abrir_modal('{% url 'psicologa:info' postulante.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulante.nombre}} {{postulante.apellido_p}} {{postulante.apellido_m}}</a>
                </td>
                <td class="text-center">{{postulante.cargo}}</td>
                <td class="text-center"> {{postulante.colegio1}}</td>

                <td style="text-align: center;">{{postulante.años}}</td >
                <td class="text-center"><a href="{{postulante.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
                <td class="text-center">{{postulante.enviada|date:"d/m/Y"}}</td>

                <td class="text-center">
                    <a href="{% url 'psicologa:rubricas' postulante.pk %}" class="btn btn-primary btn-sm"> Rúbricas</a>

                </td>
                <td class="text-center">
                    <a href="{% url 'psicologa:rubrica' postulante.pk %}" class="btn btn-primary btn-sm pulse"> Entrevistar</a>
                </td>
            </tr>
            {% endif %}
        {% endif %}
        {% if user.psicologa.psicologa2 %}
        {% if postulante.psicologa2 %}

        <tr>
            <td class="text-center">
                <a onclick="return abrir_modal('{% url 'psicologa:info' postulante.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulante.nombre}} {{postulante.apellido_p}} {{postulante.apellido_m}}</a>
            </td>
            <td class="text-center">{{postulante.cargo}}</td>
            <td class="text-center"> {{postulante.colegio1}}</td>

            <td style="text-align: center;">{{postulante.años}}</td >
            <td class="text-center"><a href="{{postulante.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
            <td class="text-center">{{postulante.enviada|date:"d/m/Y"}}</td>

            <td class="text-center">
                <a href="{% url 'psicologa:rubricas' postulante.pk %}" class="btn btn-primary btn-sm"> Rúbricas</a>

            </td>
            <td class="text-center">
                <a href="{% url 'psicologa:rubrica' postulante.pk %}" class="btn btn-primary btn-sm pulse"> Entrevistar</a>
            </td>
        </tr>
        {% endif %}
    {% endif %}
        {% endfor %}

        {% for postulantes_c in postulantes_c %}
        {% if user.psicologa.psicologa1 %}
        {% if postulantes_c.postulacion.psicologa1 %}
        <tr>
            <td class="text-center"><a onclick="return abrir_modal('{% url 'psicologa:info' postulantes_c.postulacion.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulantes_c.postulacion.nombre}} {{postulantes_c.postulacion.apellido_p}} {{postulantes_c.postulacion.apellido_m}}</a></td>

            <td class="text-center">{{postulantes_c.postulacion.cargo}}</td>
            <td  class="text-center" style="text-align: center;"> {{postulantes_c.postulacion.colegio1}}</td>

            <td class="text-center" style="text-align: center;">{{postulantes_c.postulacion.años}}</td >
            <td class="text-center"><a href="{{postulantes_c.postulacion.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
            <td class="text-center">{{postulantes_c.postulacion.enviada|date:"d/m/Y"}}</td>

            <td class="text-center">
                <a href="{% url 'psicologa:vista_rubrica_coordinador' postulantes_c.pk %}" class="btn btn-primary btn-sm"> Rubrica</a>
            </td>
            <td class="text-center">
                <a href="{% url 'psicologa:rubrica' postulantes_c.postulacion.pk %}" class="btn btn-primary btn-sm pulse"> Entrevistar</a>
            </td>
        </tr>
        {% endif %}
        {% endif %}
        {% if user.psicologa.psicologa2 %}
        {% if postulantes_c.postulacion.psicologa2 %}

        <tr>
            <td class="text-center"><a onclick="return abrir_modal('{% url 'psicologa:info' postulantes_c.postulacion.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulantes_c.postulacion.nombre}} {{postulantes_c.postulacion.apellido_p}} {{postulantes_c.postulacion.apellido_m}}</a></td>

            <td class="text-center">{{postulantes_c.postulacion.cargo}}</td>
            <td  class="text-center" style="text-align: center;"> {{postulantes_c.postulacion.colegio1}}</td>

            <td class="text-center" style="text-align: center;">{{postulantes_c.postulacion.años}}</td >
            <td class="text-center"><a href="{{postulantes_c.postulacion.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
            <td class="text-center">{{postulantes_c.postulacion.enviada|date:"d/m/Y"}}</td>

            <td class="text-center">
                <a href="{% url 'psicologa:vista_rubrica_coordinador' postulantes_c.pk %}" class="btn btn-primary btn-sm"> Rubrica</a>
            </td>
            <td class="text-center">
                <a href="{% url 'psicologa:rubrica' postulantes_c.postulacion.pk %}" class="btn btn-primary btn-sm pulse"> Entrevistar</a>
            </td>
        </tr>
        {% endif %}
        {% endif %}
        {% endfor %}

        {% for postulantes_c in postulante_em %}
        {% if user.psicologa.psicologa1 %}
        {% if postulantes_c.postulacion.psicologa1 %}
        <tr>
            <td class="text-center"><a onclick="return abrir_modal('{% url 'psicologa:info' postulantes_c.postulacion.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulantes_c.postulacion.nombre}} {{postulantes_c.postulacion.apellido_p}} {{postulantes_c.postulacion.apellido_m}}</a></td>

            <td class="text-center">{{postulantes_c.postulacion.cargo}}</td>
            <td  class="text-center" style="text-align: center;"> {{postulantes_c.postulacion.colegio1}}</td>
            <td class="text-center" style="text-align: center;">{{postulantes_c.postulacion.años}}</td >
            <td class="text-center"><a href="{{postulantes_c.postulacion.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
            <td class="text-center">{{postulantes_c.postulacion.enviada|date:"d/m/Y"}}</td>

            <td class="text-center">
                <a href="{% url 'psicologa:vista_rubrica_equipo' postulantes_c.pk %}" class="btn btn-primary btn-sm"> Rubricas</a>
            </td>
            <td class="text-center">
                <a href="{% url 'psicologa:rubrica' postulantes_c.postulacion.pk %}" class="btn btn-primary btn-sm pulse"> Entrevistar</a>
            </td>
        </tr>
        {% endif %}
        {% endif %}
        {% if user.psicologa.psicologa2 %}
        {% if postulantes_c.postulacion.psicologa2 %}
        <tr>
            <td class="text-center"><a onclick="return abrir_modal('{% url 'psicologa:info' postulantes_c.postulacion.pk %}','Postulante')" data-toggle="tooltip"  title="Ver Información">{{postulantes_c.postulacion.nombre}} {{postulantes_c.postulacion.apellido_p}} {{postulantes_c.postulacion.apellido_m}}</a></td>

            <td class="text-center">{{postulantes_c.postulacion.cargo}}</td>
            <td  class="text-center" style="text-align: center;"> {{postulantes_c.postulacion.colegio1}}</td>
            <td class="text-center" style="text-align: center;">{{postulantes_c.postulacion.años}}</td >
            <td class="text-center"><a href="{{postulantes_c.postulacion.cv.url}}" target="_blank"><i class="fas fa-file-download"></i></a></td>
            <td class="text-center">{{postulantes_c.postulacion.enviada|date:"d/m/Y"}}</td>

            <td class="text-center">
                <a href="{% url 'psicologa:vista_rubrica_equipo' postulantes_c.pk %}" class="btn btn-primary btn-sm"> Rubricas</a>
            </td>
            <td class="text-center">
                <a href="{% url 'psicologa:rubrica' postulantes_c.postulacion.pk %}" class="btn btn-primary btn-sm pulse"> Entrevistar</a>
            </td>
        </tr>
        {% endif %}
        {% endif %}
        {% endfor %}
        </tbody>
    </table>



</div>

<div id="popup"></div>



<script>
    var modal;
    function abrir_modal(url, titulo)
    {
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 900,
            resizable: false
        }).dialog('open').load(url)
    }

    function cerrar_modal()
    {
        modal.dialog("close");
    }
</script>

{% endblock %}

CV_APP/templates/psicologa/rubricas.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}



<br>
<h1 class="text-center">Rúbricas</h1>
<p>Postulante: {{postulacion.nombre}} {{postulacion.apellido_p}} {{postulacion.apellido_m}} </p>
<p>Colegio: {{postulacion.colegio1}}</p>
<br>
<div class="row">
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        Coordinador/a FFEBE que entrevistó:
      </div>
      <div class="card-body">
        <p class="card-text text-center">{{postulacion.coordinador_entrevisto}}</p>
      </div>
    </div>
    
  </div>
  <div class="col-sm-6">
    <div class="card " >
      <div class="card-header">
        Observaciones Coordinador/a FEBE:
      </div>
      <div class="card-body">
        <p class="card-text">{{postulacion.observaciones_c}}</p>
      </div>
    </div>

  </div>
</div>
<br>
<div class="container">
    <div class="row">

        {% for postulante in postulantes %}
    
        <div class="col-sm-4">
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Rúbrica entrevista rector</h5>
              <p class="card-text">Publicación: {{postulante.realizada|date:"d/m/Y"}}</p>
    
              <a href="{% url 'psicologa:vista_rubrica' postulante.pk %}" class="btn btn-primary btn-lg">Ver </a>
            </div>
          </div>
        </div>
        {% endfor %}
    
        {% for postulante_c in postulante_c %}
    
        <div class="col-sm-4">
          <div class="card" style="width: 18rem;"> 
            <div class="card-body">
              <h5 class="card-title">Ver rúbrica coordinador</h5>
              <p class="card-text">Publicación: {{postulante_c.realizada|date:"d/m/Y"}}</p>
              <a href="{% url 'psicologa:vista_rubrica_coordinador' postulante_c.pk %}" class="btn btn-primary btn-lg"> Ver </a>
            </div>
          </div>
        </div>
        {% endfor %}
    
        {% for postulante_em in postulante_em %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;"> 
              <div class="card-body">
                <h5 class="card-title">Rúbrica equipo multidiciplinario</h5>
                <p class="card-text">Publicación: {{postulante_em.realizada|date:"d/m/Y"}}</p>
                <a href="{% url 'psicologa:vista_rubrica_equipo' postulante_em.pk %}" class="btn btn-primary btn-lg"> Ver </a>
            </div>
            </div>
        </div>
        {% endfor %}
    
        {% for postulante_demo in postulante_demo %}
        
        <div class="col-sm-4">
    
            <div class="card" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">Rúbrica clase demostrativa</h5>
                <p class="card-text">Publicación: {{postulante_demo.realizada|date:"d/m/Y"}}</p>
                <a href="{% url 'psicologa:vista_rubrica_demo' postulante_demo.pk %}" class="btn btn-primary btn-lg"> Ver</a>
            </div>
            </div>
          </div>
          {% endfor %}
          
          {% for postulante_psicologa in postulante_psicologa %}
          
          <div class="col-sm-4">
            <div class="card" style="width: 18rem;"> 
              <div class="card-body">
                <h5 class="card-title">Rúbrica psicóloga</h5>
                <p class="card-text">Publicación: {{postulante_psicologa.realizada|date:"d/m/Y"}}</p>
                <a href="{% url 'psicologa:vista_rubrica_psicologa' postulante_psicologa.pk %}" class="btn btn-primary btn-lg"> Ver </a>
            </div>
            </div>
          </div>
          {% endfor %}
    

    
    </div>
</div>
<div id="popup"></div>


<script>
    var modal;
    function abrir_modal(url, titulo)
    {
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 900,
            resizable: false
        }).dialog('open').load(url)
    }

    function cerrar_modal()
    {
        modal.dialog("close");
    }
</script>

{% endblock %}